### ISSUE TITLE
[Curitiba] Desenvolvedor PHP Pleno

### ISSUE THREAD

**Issue by rdehnhardt** [phppr/vagas#1]
## Descrição da vaga

Atuar no desenvolvimento e manutenção de sistemas próprio em php, html, javascript.

## Local

Escritório, Curitiba - Centro

## Benefícios
- Vale Transporte
- Vale Refeição
- Plano de Saúde
- Seguro de Vida.

## Requisitos

  **Obrigatórios:**
  - PHP
  - Symfony framework
  - Laravel Framework
  - Orientação a Objetos
  - MySql,
  - Javascript
  - CSS3
  - HTML 5

  **Desejáveis:**
  - Integrações SOAP / REST
  - AWS

**Diferenciais:**
- Front-End Frameworks (Angular, Aurelia, Ember, ...)

## Contratação

CLT / Salário a combinar

## Nossa empresa

Rentcars.com é principal site de comparação de preços e locação de veículos da América Latina.

Criado em Janeiro de 2009, somos líderes no mercado brasileiro de emissões de reservas junto às principais redes de locadoras de veículos no mundo.

## Como se candidatar

Por favor envie um email para renato.dehnhardt@rentcars.com com seu perfil do Github e Linkedin - enviar no assunto: Vaga PHP.

**Comment by nandomoreirame** [comment]
Primeira vaga divulgada no PHP PR, obrigado por compartilhar @rdehnhardt vamos divulgar :+1:

**Comment by rdehnhardt** [comment]
@nandomoreirame não consegui adicionar as labels, o github não permitiu, pode ser alguma configuração?

**Comment by nandomoreirame** [comment]
Acho que só membros da Organização que podem alterar algo no projeto podem adicionar, alterar e remover labels, não tenho certeza.
