### ISSUE TITLE
VAGA INVÁLIDA

### ISSUE THREAD

**Issue by devbrunocorrea** [phppr/vagas#21]
Interessados preencher o formulário:

https://docs.google.com/forms/d/1-L8Jxut7defyTPW6utCwXLqWNbtfJPgbG5LbwJaegAg/viewform?edit_requested=true

**Comment by nandomoreirame** [comment]
Favor preencher como no modelo:

---

## Descrição da vaga

Trabalhar em um projeto tesão pia...

## Local

Remoto ou Escritório, Curitiba - Centro

## Benefícios
- 2 horas de almoço
- Monte a sua máquina como desejar
- Frigobar sempre cheio :P
- Sala de jogos
- ...

## Requisitos

  **Obrigatórios:**
  - 3 anos de experiência com PHP
  - 2 anos de experiência com MySQL ou similar

  **Desejáveis:**
  - Conhecimentos em Docker
  - Conhecimentos em AWS

**Diferenciais:**
- Contribuição em projetos opensource

## Contratação

CLT a salário a combinar

## Nossa empresa

Aqui na Corporação XPTO somos líderes em...

## Como se candidatar

Por favor envie um email para email@email.com.br com seu perfil do Github e CV anexado - enviar no assunto: Vaga Dev PHP

**Comment by nandomoreirame** [comment]
@marcelosousa46 era apenas um modelo, @devbrunocorrea não colocou nenhum modelo, apenas um formulário para cadastro, mas vou classificar como vaga inválida se não tiver os dados completos.

**Comment by marcelosousa46** [comment]
Entendido, grato!

*Marcelo Sousa*
Programador
*(85) 99176-0967*

Tecnologias:
PHP/Laravel,
Python/Django
Delphi



Em ter, 21 de ago de 2018 às 17:38, Fernando Moreira <
notifications@github.com> escreveu:
