### ISSUE TITLE
[Curitiba] Desenvolvedor PHP PL/Senior

### ISSUE THREAD

**Issue by andrebian** [phppr/vagas#6]
## Descrição da vaga

Procuramos um desenvolvedor PHP que conheça PHP, html, Javascript e CSS. Também é necessário bom conhecimento em desenvolvimento orientado a objetos e banco de dados Mysql. Buscamos um profissional que queira crescer, contribuir para o crescimento da empresa e  trazer ideias para discussão.

## Local

Curitiba - PR

## Benefícios

- Horário semi-flexível (cobramos por produtividade)
- Trabalhará com profissionais que não cansam de aprender
- Demais benefícios conforme acertado na contratação

## Requisitos

  **Obrigatórios:**
 - Experiência com desenvolvimento web PHP, HTML, Javascript, CSS
 - Conhecimento em banco de dados relacional (elaboração de consultas, stored procedures, triggers)
 - Bom conhecimento de modelagem orientada a objetos
 - Bom conhecimento do Git (ou outro DVCS)
 - Consumo, modelagem e implementação de APIs Restful
 - Facilidade em compreender documentações técnicas e especificações
 - Curso superior na área de computação ou experiência equivalente
 - Experiência com as metodologias ágeis
 - Ter participado de pelo menos 1 (um) projeto em sua totalidade (idealização, levantamento de requisitos, desenvolvimento, implantação e manutenção/evolução)
 - Noções de segurança de sistemas web
 - Inglês avançado ou fluente

  **Desejáveis:**
 - Experiência com Zend Framework 2, Doctrine ORM e Composer
 - Experiência com Firebase
 - Experiência com testes de software
 - Compreensão dos principais padrões de projeto (e suas aplicações)

**Diferenciais:**
- Contribuição em projetos opensource
- Contribuição com palestras em eventos de software, dentro de empresas ou em instituições de ensino.

## Contratação

CLT ou PJ

## Nossa empresa

A 4ITIL, é uma empresa especializada em consultoria de serviços de internet, infraestrutura de TI, e CRM (Relacionamento com clientes), com grande experiência no mercado de tecnologia e objetivo de fornecer soluções personalizadas com qualidade, visando a satisfação do cliente.

## Como se candidatar

Por favor envie um email para andre@4itil.com.br com seu perfil do Github e CV anexado - enviar no assunto: Vaga Dev PHP

**Comment by andretx** [comment]
Ainda está precisando?

**Comment by andrebian** [comment]
@andretx esqueci de encerrar. Infelizmente não mais. A empresa optou por terceirizar programadores :(
