### ISSUE TITLE
[Curitiba e Região] Analista Desenvolvedor PHP

### ISSUE THREAD

**Issue by cesarmiggiolaro** [phppr/vagas#9]
## Descrição da vaga

Trabalhar em projetos na área de saúde. Ter conhecimento nível Pleno ou Sênior no desenvolvimento em PHP.  

## Local

Curitiba - Centro Cívico 

## Benefícios
- 8 Horas diárias flexíveis - a combinar  
- VR
- VT
- PPRL

## Requisitos

  **Obrigatórios:**
  - PHP
  - Symfony framework
  - PostgreSql
  - Conhecimentos básicos de LINUX
  - GIT

  **Desejáveis:**
  - Integrações REST
  - AngularJs
  - Preocupação com segurança
  - Preocupação com performance
  - Preocupação com documentação

## Contratação

CLT a salário a combinar

Segunda a Sexta-feira, 8 horas diárias  

## Nossa empresa

A 2iM® foi criada, em 2011, a partir de um spin off da Impacto Tecnologias Gerenciais em Saúde, empresa controladora da mesma. Tem como objetivo, prover ao mercado, soluções focadas no conceito de Business Analytics em Saúde, onde se propõe a disponibilização de Inteligência Médica a partir da consolidação de dados gerados por diversos sistemas de gestão existentes e a produção de informações e conhecimentos gerenciais e estratégicos.

## Como se candidatar

Por favor envie um email para cesar.miggiolaro@2im.com.br com seu CV anexado e pretensão salarial - enviar no assunto: Vaga Analista PHP

**Comment by cesarmiggiolaro** [comment]
Boa Tarde, obrigado a todos que enviaram Currículos. Fechamos uma contratação, assim que abrir nova vaga, volta anunciar aqui no grupo. Obrigado

**Comment by nandomoreirame** [comment]
:+1:
